-- Esquema local reconstruido a partir das entidades e consultas JDBC do projeto.
-- Nenhuma tabela existente e apagada por este arquivo.
CREATE DATABASE IF NOT EXISTS ssdparaviverbem CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ssdparaviverbem;

CREATE TABLE IF NOT EXISTS EMPRESA_01 (
 A01_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A01_NOME VARCHAR(200) NOT NULL,
 A01_DESCRICAO TEXT,
 A01_STATUS INT NOT NULL DEFAULT 1,
 A01_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A01_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS USUARIO_02 (
 A02_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A02_NOME VARCHAR(200) NOT NULL,
 A02_USUARIO VARCHAR(100) NOT NULL UNIQUE,
 A02_SENHA VARCHAR(255) NOT NULL,
 A02_CODIGO_LINK VARCHAR(100),
 A02_EMAIL VARCHAR(255),
 A02_STATUS INT NOT NULL DEFAULT 1,
 A02_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A02_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX IX_USUARIO_LINK (A02_CODIGO_LINK)
);
CREATE TABLE IF NOT EXISTS EMPRESA_USUARIO_PERFIL_03 (
 A01_CODIGO BIGINT NOT NULL,
 A02_CODIGO BIGINT NOT NULL,
 A03_PERFIL_PARAVIVERBEM INT NOT NULL DEFAULT 0,
 A03_PERFIL_ADMINISTRADOR INT NOT NULL DEFAULT 0,
 A03_PERFIL_CHEFE INT NOT NULL DEFAULT 0,
 A03_PERFIL_PADRAO INT NOT NULL DEFAULT 1,
 A03_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (A01_CODIGO,A02_CODIGO),
 FOREIGN KEY (A01_CODIGO) REFERENCES EMPRESA_01(A01_CODIGO),
 FOREIGN KEY (A02_CODIGO) REFERENCES USUARIO_02(A02_CODIGO)
);
CREATE TABLE IF NOT EXISTS AGENDA_04 (
 A04_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A01_CODIGO BIGINT NOT NULL,
 A04_TITULO VARCHAR(255) NOT NULL,
 A04_DESCRICAO TEXT,
 A04_STATUS_DT_LIMITE INT NOT NULL DEFAULT 0,
 A04_DATA_LIMITE DATE,
 A04_RESULTADO VARCHAR(255) DEFAULT '',
 A04_CERTEZA_RESULTADO DOUBLE NOT NULL DEFAULT 0,
 A04_CONTRADICAO_RESULTADO DOUBLE NOT NULL DEFAULT 0,
 A04_STATUS INT NOT NULL DEFAULT 0,
 A04_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A04_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (A01_CODIGO) REFERENCES EMPRESA_01(A01_CODIGO)
);
CREATE TABLE IF NOT EXISTS USUARIO_AGENDA_05 (
 A05_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A04_CODIGO BIGINT NOT NULL,
 A02_CODIGO BIGINT NOT NULL,
 A05_NUM_SEQUENCIA BIGINT NOT NULL DEFAULT 0,
 A05_PERFIL_AGENDA_USUARIO_TITULAR INT NOT NULL DEFAULT 0,
 A05_PERFIL_AGENDA_USUARIO_FACILITADOR INT NOT NULL DEFAULT 0,
 A05_PERFIL_AGENDA_USUARIO_ESPECIALISTA INT NOT NULL DEFAULT 0,
 A05_PERFIL_AGENDA_USUARIO_ANALISTA INT NOT NULL DEFAULT 0,
 A05_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A05_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_USUARIO_AGENDA (A04_CODIGO,A02_CODIGO),
 FOREIGN KEY (A04_CODIGO) REFERENCES AGENDA_04(A04_CODIGO),
 FOREIGN KEY (A02_CODIGO) REFERENCES USUARIO_02(A02_CODIGO)
);
CREATE TABLE IF NOT EXISTS FATOR_06 (
 A06_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A04_CODIGO BIGINT NOT NULL,
 A02_CODIGO BIGINT NOT NULL,
 A06_TITULO VARCHAR(255) NOT NULL,
 A06_DESCRICAO TEXT,
 A06_NUM_SEQUENCIA INT NOT NULL DEFAULT 0,
 A06_CERTEZA_RESULTANTE_FATOR DOUBLE NOT NULL DEFAULT 0,
 A06_CONTRADICAO_RESULTANTE_FATOR DOUBLE NOT NULL DEFAULT 0,
 A06_RESULTADO_FATOR VARCHAR(255) DEFAULT '',
 A06_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A06_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (A04_CODIGO) REFERENCES AGENDA_04(A04_CODIGO),
 FOREIGN KEY (A02_CODIGO) REFERENCES USUARIO_02(A02_CODIGO)
);
CREATE TABLE IF NOT EXISTS PARECER_FATOR_USUARIO_07 (
 A07_CODIGO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 A06_CODIGO BIGINT NOT NULL,
 A02_CODIGO BIGINT NOT NULL,
 A07_NUM_SEQUENCIA INT NOT NULL DEFAULT 0,
 A07_CERTEZA DOUBLE NULL,
 A07_CONTRADICAO DOUBLE NULL,
 A07_DT_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 A07_DT_ULTIMA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_PARECER_FATOR_USUARIO (A06_CODIGO,A02_CODIGO),
 FOREIGN KEY (A06_CODIGO) REFERENCES FATOR_06(A06_CODIGO),
 FOREIGN KEY (A02_CODIGO) REFERENCES USUARIO_02(A02_CODIGO)
);

CREATE OR REPLACE VIEW VW_PARTICIPANTES_AGENDA AS
 SELECT A.*, UA.A02_CODIGO FROM AGENDA_04 A
 INNER JOIN USUARIO_AGENDA_05 UA ON UA.A04_CODIGO=A.A04_CODIGO;

CREATE OR REPLACE VIEW VW_AGENDAS_USUARIOS AS
 SELECT UA.*, U.A02_NOME FROM USUARIO_AGENDA_05 UA
 INNER JOIN USUARIO_02 U ON U.A02_CODIGO=UA.A02_CODIGO;

CREATE OR REPLACE VIEW VW_AGENDAS_FATORES AS
 SELECT F.*, U.A02_NOME FROM FATOR_06 F
 INNER JOIN USUARIO_02 U ON U.A02_CODIGO=F.A02_CODIGO;

CREATE OR REPLACE VIEW VW_FATORES_PARECERES AS
 SELECT P.*, F.A04_CODIGO, F.A06_TITULO, U.A02_NOME
 FROM PARECER_FATOR_USUARIO_07 P
 INNER JOIN FATOR_06 F ON F.A06_CODIGO=P.A06_CODIGO
 INNER JOIN USUARIO_02 U ON U.A02_CODIGO=P.A02_CODIGO;

-- Rotinas opcionais para os metodos legados Xinsert* (fora do fluxo normal).
DELIMITER $$
CREATE PROCEDURE IF NOT EXISTS PROC_INS_USUARIO2(
 IN p_nome VARCHAR(200), IN p_usuario VARCHAR(100), IN p_senha VARCHAR(255),
 IN p_email VARCHAR(255), IN p_link VARCHAR(100), IN p_status INT, IN p_chave VARCHAR(255))
BEGIN
 INSERT INTO USUARIO_02(A02_NOME,A02_USUARIO,A02_SENHA,A02_EMAIL,A02_CODIGO_LINK,A02_STATUS)
 VALUES(p_nome,p_usuario,p_senha,p_email,p_link,p_status);
END$$
CREATE PROCEDURE IF NOT EXISTS PROC_INS_EMPRESA_USUARIO_PERFIL2(
 IN p_empresa BIGINT, IN p_usuario BIGINT, IN p_pvb INT, IN p_admin INT, IN p_chefe INT, IN p_padrao INT)
BEGIN
 INSERT INTO EMPRESA_USUARIO_PERFIL_03(A01_CODIGO,A02_CODIGO,A03_PERFIL_PARAVIVERBEM,
 A03_PERFIL_ADMINISTRADOR,A03_PERFIL_CHEFE,A03_PERFIL_PADRAO)
 VALUES(p_empresa,p_usuario,p_pvb,p_admin,p_chefe,p_padrao);
END$$
DELIMITER ;
