begin;

create table if not exists empresa_01 (
 a01_codigo bigint generated by default as identity primary key,
 a01_nome varchar(200) not null,
 a01_descricao text,
 a01_status int not null default 1,
 a01_dt_cadastro timestamp not null default current_timestamp,
 a01_dt_ultima_alteracao timestamp default current_timestamp
);
create table if not exists usuario_02 (
 a02_codigo bigint generated by default as identity primary key,
 a02_nome varchar(200) not null,
 a02_usuario varchar(100) not null unique,
 a02_senha varchar(255) not null,
 a02_codigo_link varchar(100),
 a02_email varchar(255),
 a02_status int not null default 1,
 a02_dt_cadastro timestamp not null default current_timestamp,
 a02_dt_ultima_alteracao timestamp default current_timestamp
);
create table if not exists empresa_usuario_perfil_03 (
 a01_codigo bigint not null,
 a02_codigo bigint not null,
 a03_perfil_paraviverbem int not null default 0,
 a03_perfil_administrador int not null default 0,
 a03_perfil_chefe int not null default 0,
 a03_perfil_padrao int not null default 1,
 a03_dt_cadastro timestamp not null default current_timestamp,
 primary key (a01_codigo,a02_codigo),
 foreign key (a01_codigo) references empresa_01(a01_codigo),
 foreign key (a02_codigo) references usuario_02(a02_codigo)
);
create table if not exists agenda_04 (
 a04_codigo bigint generated by default as identity primary key,
 a01_codigo bigint not null,
 a04_titulo varchar(255) not null,
 a04_descricao text,
 a04_status_dt_limite int not null default 0,
 a04_data_limite date,
 a04_resultado varchar(255) default '',
 a04_certeza_resultado double precision not null default 0,
 a04_contradicao_resultado double precision not null default 0,
 a04_status int not null default 0,
 a04_dt_cadastro timestamp not null default current_timestamp,
 a04_dt_ultima_alteracao timestamp default current_timestamp,
 foreign key (a01_codigo) references empresa_01(a01_codigo)
);
create table if not exists usuario_agenda_05 (
 a05_codigo bigint generated by default as identity primary key,
 a04_codigo bigint not null,
 a02_codigo bigint not null,
 a05_num_sequencia bigint not null default 0,
 a05_perfil_agenda_usuario_titular int not null default 0,
 a05_perfil_agenda_usuario_facilitador int not null default 0,
 a05_perfil_agenda_usuario_especialista int not null default 0,
 a05_perfil_agenda_usuario_analista int not null default 0,
 a05_dt_cadastro timestamp not null default current_timestamp,
 a05_dt_ultima_alteracao timestamp default current_timestamp,
 unique (a04_codigo,a02_codigo),
 foreign key (a04_codigo) references agenda_04(a04_codigo),
 foreign key (a02_codigo) references usuario_02(a02_codigo)
);
create table if not exists fator_06 (
 a06_codigo bigint generated by default as identity primary key,
 a04_codigo bigint not null,
 a02_codigo bigint not null,
 a06_titulo varchar(255) not null,
 a06_descricao text,
 a06_num_sequencia int not null default 0,
 a06_certeza_resultante_fator double precision not null default 0,
 a06_contradicao_resultante_fator double precision not null default 0,
 a06_resultado_fator varchar(255) default '',
 a06_dt_cadastro timestamp not null default current_timestamp,
 a06_dt_ultima_alteracao timestamp default current_timestamp,
 foreign key (a04_codigo) references agenda_04(a04_codigo),
 foreign key (a02_codigo) references usuario_02(a02_codigo)
);
create table if not exists parecer_fator_usuario_07 (
 a07_codigo bigint generated by default as identity primary key,
 a06_codigo bigint not null,
 a02_codigo bigint not null,
 a07_num_sequencia int not null default 0,
 a07_certeza double precision null,
 a07_contradicao double precision null,
 a07_dt_cadastro timestamp not null default current_timestamp,
 a07_dt_ultima_alteracao timestamp default current_timestamp,
 unique (a06_codigo,a02_codigo),
 foreign key (a06_codigo) references fator_06(a06_codigo),
 foreign key (a02_codigo) references usuario_02(a02_codigo)
);

create or replace view vw_participantes_agenda as
 select a.*, ua.a02_codigo from agenda_04 a
 inner join usuario_agenda_05 ua on ua.a04_codigo=a.a04_codigo;

create or replace view vw_agendas_usuarios as
 select ua.*, u.a02_nome from usuario_agenda_05 ua
 inner join usuario_02 u on u.a02_codigo=ua.a02_codigo;

create or replace view vw_agendas_fatores as
 select f.*, u.a02_nome from fator_06 f
 inner join usuario_02 u on u.a02_codigo=f.a02_codigo;

create or replace view vw_fatores_pareceres as
 select p.*, f.a04_codigo, f.a06_titulo, u.a02_nome
 from parecer_fator_usuario_07 p
 inner join fator_06 f on f.a06_codigo=p.a06_codigo
 inner join usuario_02 u on u.a02_codigo=p.a02_codigo;


create or replace view vw_usuario_empresas as select e.*, p.a02_codigo, p.a03_perfil_paraviverbem, p.a03_perfil_administrador, p.a03_perfil_chefe, p.a03_perfil_padrao, p.a03_dt_cadastro from empresa_01 e join empresa_usuario_perfil_03 p on p.a01_codigo=e.a01_codigo;
create or replace view vw_empresa_usuarios as select u.*, p.a01_codigo, p.a03_perfil_paraviverbem, p.a03_perfil_administrador, p.a03_perfil_chefe, p.a03_perfil_padrao, p.a03_dt_cadastro from usuario_02 u join empresa_usuario_perfil_03 p on p.a02_codigo=u.a02_codigo;

-- A aplicação Java autentica e autoriza. Nenhum acesso público por anon.
alter table empresa_01 enable row level security;
alter table usuario_02 enable row level security;
alter table empresa_usuario_perfil_03 enable row level security;
alter table agenda_04 enable row level security;
alter table usuario_agenda_05 enable row level security;
alter table fator_06 enable row level security;
alter table parecer_fator_usuario_07 enable row level security;
revoke all on empresa_01 from anon, authenticated;
grant all on empresa_01 to service_role;
revoke all on usuario_02 from anon, authenticated;
grant all on usuario_02 to service_role;
revoke all on empresa_usuario_perfil_03 from anon, authenticated;
grant all on empresa_usuario_perfil_03 to service_role;
revoke all on agenda_04 from anon, authenticated;
grant all on agenda_04 to service_role;
revoke all on usuario_agenda_05 from anon, authenticated;
grant all on usuario_agenda_05 to service_role;
revoke all on fator_06 from anon, authenticated;
grant all on fator_06 to service_role;
revoke all on parecer_fator_usuario_07 from anon, authenticated;
grant all on parecer_fator_usuario_07 to service_role;
revoke all on vw_participantes_agenda from anon, authenticated;
grant all on vw_participantes_agenda to service_role;
revoke all on vw_agendas_usuarios from anon, authenticated;
grant all on vw_agendas_usuarios to service_role;
revoke all on vw_agendas_fatores from anon, authenticated;
grant all on vw_agendas_fatores to service_role;
revoke all on vw_fatores_pareceres from anon, authenticated;
grant all on vw_fatores_pareceres to service_role;
revoke all on vw_usuario_empresas from anon, authenticated;
grant all on vw_usuario_empresas to service_role;
revoke all on vw_empresa_usuarios from anon, authenticated;
grant all on vw_empresa_usuarios to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Somente ambiente de teste: usuário admin, senha admin. Não altera senha existente.
insert into empresa_01(a01_nome,a01_descricao) select 'Empresa de Testes','Ambiente de estudo ParaDecision' where not exists(select 1 from empresa_01 where a01_nome='Empresa de Testes');
insert into usuario_02(a02_nome,a02_usuario,a02_senha,a02_email,a02_status) values('Administrador','admin','pbkdf2$2k+spY21kcv8H1EZSz+NDw==$we2lgofoq8VILG5IKla78yMtBDk3MPJ6TSNIlCvjwwM=','admin@example.test',1) on conflict(a02_usuario) do nothing;
insert into empresa_usuario_perfil_03(a01_codigo,a02_codigo,a03_perfil_administrador,a03_perfil_chefe,a03_perfil_padrao) select e.a01_codigo,u.a02_codigo,1,1,1 from empresa_01 e cross join usuario_02 u where e.a01_nome='Empresa de Testes' and u.a02_usuario='admin' on conflict(a01_codigo,a02_codigo) do nothing;

commit;
