import {useState} from 'react';
import {agendas} from './api.js';
import {empresas} from '../empresas/api.js';
import {useConsulta,Consulta,Formulario,Check,Aviso} from '../compartilhado/components.jsx';
export default function Participantes({agenda,empresa,podeEditar,onChange}) {
  const c=useConsulta(()=>agendas.participantes(agenda.id),[agenda.id]);
  const disponiveis=useConsulta(()=>empresa.podeGerenciar?empresas.usuarios(empresa.id):Promise.resolve([]),[empresa.id]);
  const [edicao,setEdicao]=useState(null),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false);
  async function remover(id){if(!window.confirm('Remover este participante da agenda?'))return;setOcupado(true);setErro('');try{await agendas.remover(agenda.id,id);c.recarregar();onChange()}catch(e){setErro(e.message)}finally{setOcupado(false)}}
  return <><div className="titulo"><h2>Participantes</h2>{podeEditar&&agenda.status!==9&&<button onClick={()=>setEdicao({usuario:{},perfil:{especialista:true}})}>+ Vincular usuário</button>}</div><Aviso erro={erro}/>{edicao&&<section className="card" key={edicao.usuario.id||'novo'}><Formulario onCancel={()=>setEdicao(null)} onSubmit={async d=>{await agendas.vincular(agenda.id,edicao.usuario.id||Number(d.usuario),{titular:d.titular==='on',facilitador:d.facilitador==='on',especialista:d.especialista==='on',analista:d.analista==='on'});setEdicao(null);c.recarregar();onChange()}}>{edicao.usuario.id?<h3>{edicao.usuario.nome}</h3>:<Consulta consulta={disponiveis}>{lista=><label className="campo">Usuário da empresa<select name="usuario" required defaultValue=""><option value="" disabled>Selecione</option>{lista.map(p=><option key={p.usuario.id} value={p.usuario.id}>{p.usuario.nome}</option>)}</select>{!empresa.podeGerenciar&&<small>Peça a um gestor da empresa para adicionar novos participantes.</small>}</label>}</Consulta>}{['titular','facilitador','especialista','analista'].map(p=><Check key={p} name={p} label={p[0].toUpperCase()+p.slice(1)} defaultChecked={edicao.perfil[p]}/>)}</Formulario></section>}<Consulta consulta={c}>{lista=>lista.length?<div className="lista">{lista.map(p=><div className="linha" key={p.usuario.id}><div><h3>{p.usuario.nome}</h3><p>{Object.entries(p.perfil).filter(([,v])=>v).map(([k])=>k).join(' · ')||'Sem perfil'}</p></div>{podeEditar&&agenda.status!==9&&<div className="acoes"><button disabled={ocupado} onClick={()=>setEdicao(p)}>Editar perfis</button><button disabled={ocupado} onClick={()=>remover(p.usuario.id)}>Remover</button></div>}</div>)}</div>:<p className="vazio">Nenhum participante cadastrado.</p>}</Consulta></>;
}
