import fs from 'node:fs';
import {pbkdf2Sync,randomBytes} from 'node:crypto';
const mysql=fs.readFileSync('banco/schema.sql','utf8').split('-- Rotinas opcionais')[0];
let sql=mysql.replace(/^CREATE DATABASE.*\r?\n|^USE .*\r?\n/gm,'').replace(/BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY/g,'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/DATETIME/g,'TIMESTAMP').replace(/ ON UPDATE CURRENT_TIMESTAMP/g,'').replace(/\bDOUBLE\b/g,'DOUBLE PRECISION').replace(/,\s*INDEX IX_USUARIO_LINK \(A02_CODIGO_LINK\)/g,'').replace(/UNIQUE KEY \w+ /g,'UNIQUE ');
sql=sql.replace(/\b[A-Z][A-Z0-9_]*\b/g,x=>x.toLowerCase());
const views=`
create or replace view vw_usuario_empresas as select e.*, p.a02_codigo, p.a03_perfil_paraviverbem, p.a03_perfil_administrador, p.a03_perfil_chefe, p.a03_perfil_padrao, p.a03_dt_cadastro from empresa_01 e join empresa_usuario_perfil_03 p on p.a01_codigo=e.a01_codigo;
create or replace view vw_empresa_usuarios as select u.*, p.a01_codigo, p.a03_perfil_paraviverbem, p.a03_perfil_administrador, p.a03_perfil_chefe, p.a03_perfil_padrao, p.a03_dt_cadastro from usuario_02 u join empresa_usuario_perfil_03 p on p.a02_codigo=u.a02_codigo;
`;
sql+=views;
const tables=['empresa_01','usuario_02','empresa_usuario_perfil_03','agenda_04','usuario_agenda_05','fator_06','parecer_fator_usuario_07'];
const all=[...tables,'vw_participantes_agenda','vw_agendas_usuarios','vw_agendas_fatores','vw_fatores_pareceres','vw_usuario_empresas','vw_empresa_usuarios'];
sql+='\n-- A aplicação Java autentica e autoriza. Nenhum acesso público por anon.\n'+tables.map(t=>`alter table ${t} enable row level security;`).join('\n')+'\n'+all.map(t=>`revoke all on ${t} from anon, authenticated;\ngrant all on ${t} to service_role;`).join('\n')+'\ngrant usage, select on all sequences in schema public to service_role;\n';
const sal=randomBytes(16);const senha=`pbkdf2$${sal.toString('base64')}$${pbkdf2Sync('admin',sal,210000,32,'sha256').toString('base64')}`;
const seed=`
-- Somente ambiente de teste: usuário admin, senha admin. Não altera senha existente.
insert into empresa_01(a01_nome,a01_descricao) select 'Empresa de Testes','Ambiente de estudo ParaDecision' where not exists(select 1 from empresa_01 where a01_nome='Empresa de Testes');
insert into usuario_02(a02_nome,a02_usuario,a02_senha,a02_email,a02_status) values('Administrador','admin','${senha}','admin@example.test',1) on conflict(a02_usuario) do nothing;
insert into empresa_usuario_perfil_03(a01_codigo,a02_codigo,a03_perfil_administrador,a03_perfil_chefe,a03_perfil_padrao) select e.a01_codigo,u.a02_codigo,1,1,1 from empresa_01 e cross join usuario_02 u where e.a01_nome='Empresa de Testes' and u.a02_usuario='admin' on conflict(a01_codigo,a02_codigo) do nothing;
`;
fs.writeFileSync('banco/supabase.sql','-- Migração PostgreSQL/Supabase. Aplicar no SQL Editor do projeto de testes.\nbegin;\n'+sql+seed+'\ncommit;\n');
fs.writeFileSync('banco/mysql-api.sql','-- Complemento do banco/schema.sql para a API REST\nUSE ssdparaviverbem;\n'+views.toUpperCase().replaceAll('CREATE OR REPLACE VIEW','CREATE OR REPLACE VIEW')+seed.replace("on conflict(a02_usuario) do nothing","ON DUPLICATE KEY UPDATE A02_USUARIO=A02_USUARIO").replace('on conflict(a01_codigo,a02_codigo) do nothing','ON DUPLICATE KEY UPDATE A01_CODIGO=EMPRESA_USUARIO_PERFIL_03.A01_CODIGO'));
